import "./stylesheets/index.css";
import { Inter } from "next/font/google";
import Layout from "@/app/components/layout";

import "regenerator-runtime/runtime";
import { LayoutProvider } from "@/app/layout-provider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>
          <Layout>
            <Layout.Navigation>
              <Layout.NavigationBrand>
                <Link href="/">Naar Holland</Link>{" "}
              </Layout.NavigationBrand>
            </Layout.Navigation>
            {children}
          </Layout>
        </LayoutProvider>
      </body>
    </html>
  );
}
